### ISSUE TITLE
Latex issues in running

### ISSUE THREAD

**Issue by amrudesh-santhanam** [Aalto-Electric-Drives/motulator#2]
Hi,

I cloned the repo, figured out it needs numpy, scipy and matplotlib to run. So, installed them and tried running simulate_sensored.py . I get issues with latex. Initially I got "RuntimeError: Failed to process string with tex because latex could not be found". I then installed latex support with `sudo apt install texlive-latex-base` . I am using ubuntu 18.04. I still see issues like "RuntimeError: latex was not able to process the following string: b'lp'". Could you please advice the right method to add latex support? Thanks.

Also, am attaching a .gitignore file and a requirements.txt file which would be good to add to the rep
[gitignore.txt](https://github.com/Aalto-Electric-Drives/motulator/files/7314961/gitignore.txt)
[requirements.txt](https://github.com/Aalto-Electric-Drives/motulator/files/7314962/requirements.txt)
o.

**Comment by mhinkkan** [comment]
Thanks for the comment. Based on this feedback, we will disable latex in the default plotting methods. This can be done by changing `plt.rcParams.update({"text.usetex": True})` to `plt.rcParams.update({"text.usetex": False})`.

**Comment by mhinkkan** [comment]
We now updated the default plotting methods so that they don't use latex fonts anymore. I close this issue now, but please inform us if this change didn't solve the problem.

**Comment by amrudesh-santhanam** [comment]
That's fine. Thnx.
