### ISSUE TITLE
Suggested example does not run on version 0.1.2

### ISSUE THREAD

**Issue by murgui** [Aalto-Electric-Drives/motulator#84]
Hi,

I just wanted to let you know that I had trouble running the example from the repository landing page in Motulator 0.1.2. The issue does not happen with version 0.1.0, which runs the example properly.

In version 0.1.2, the error is:

`File "LocalPath\Motulator\hellowWorld.py", line 16, in <module>
  File "PythonPath\motulator\plots.py", line 76, in plot
    ax2.plot(mdl.t, mdl.tau_L/base.tau, '--')
  File "PythonPath\matplotlib\axes\_axes.py", line 1635, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "PythonPath\matplotlib\axes\_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "PythonPath\matplotlib\axes\_base.py", line 498, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (8027,) and (1,)`

Thanks for this nice project.

**Comment by mhinkkan** [comment]
Thank you for contributing! PR #86 and release 0.1.4 should now fix this problem. If the problem still exists, please re-open this issue.

**Comment by mhinkkan** [comment]
@all-contributors please add @murgui  for bug
